


source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.shimo.im/ios/Specs'


target 'LargeImage' do
  pod 'SDWebImage','5.4.0'
  #pod 'SDWebImage/GIF'
  #pod 'FLAnimatedImage', '~> 1.0'
  pod 'SHMDatabase'
  pod 'BlocksKit'
  
  pod 'XTBase'
  pod 'XTTable'
  
#  pod 'XTlib'
#  pod 'XTlib/Animations'
#  pod 'XTlib/CustomUIs'
#  pod 'XTIAP'
  
#  pod 'XTBase',:path => '../../teason_project/XTBase/'
#  pod 'XTlib',:path => '../../teason_project/XTlib/'
##  pod 'XTlib/Animations',:path => '../../teason_project/XTlib/'
#  pod 'XTlib/CustomUIs',:path => '../../teason_project/XTlib/'
##  pod 'XTIAP',:path => '../XTIAP/'
  
end
